version: "3.6"

services:
  postgres:
    image: "nikolanna/custom-postgres:latest"
    ports:
      - "5432:5432"      
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    networks:
      - persistence

networks:
  persistence: {}

volumes:
  postgres-data: {}
